const STATE_CONSTANT = [ "YANGON", "MANDALAY", "NAYPYITAW", "AYARWADDY", "BAGO", "MAGWAY", "SAGAING", "TANINTHARYI", "CHIN", "KACHIN", "KAYAH", "KAYIN", "MON", "RAKHINE", "SHAN" ];

module.exports = {
    STATE_CONSTANT
}